# Generated by Django 4.2.7 on 2026-09-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('ceo', 'CEO'), ('support', 'Support')], db_index=True, max_length=20),
        ),
    ]
