# Generated by Django 4.2.7 on 2026-09-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('on', 'Active'), ('off', 'Inactive')], db_index=True, default='on', max_length=10),
        ),
    ]
